// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package mysql

import (
	"database/sql"
)

type NotificationDetail struct {
	NotificationID int64
	Email          string
	ChunkPartition string
	TaskID         string
}

type Task struct {
	TaskID       string
	TaskName     string
	CronPattern  string
	InputFileUrl string
	TaskStatus   sql.NullString
	ChunkSize    sql.NullInt32
}
